"use client";

import { Node, mergeAttributes } from "@tiptap/react";
import { ReactNodeViewRenderer, NodeViewWrapper, type ReactNodeViewProps } from "@tiptap/react";
import { useCallback, useEffect, useRef, useState } from "react";

// Mermaid node view component
function MermaidNodeView(props: ReactNodeViewProps) {
  const { node, updateAttributes, selected } = props;
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const content = (node.attrs.content as string) ?? "";
  const [isEditing, setIsEditing] = useState(!content);
  const idRef = useRef(`mermaid-${Math.random().toString(36).slice(2, 9)}`);

  const renderDiagram = useCallback(async (code: string) => {
    if (!code.trim()) {
      setSvg("");
      return;
    }
    try {
      const mermaid = (await import("mermaid")).default;
      mermaid.initialize({ startOnLoad: false, theme: "neutral", securityLevel: "strict" });
      const { svg: renderedSvg } = await mermaid.render(idRef.current, code.trim());
      setSvg(renderedSvg);
      setError("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to render diagram");
      setSvg("");
    }
  }, []);

  useEffect(() => {
    if (content && !isEditing) {
      renderDiagram(content);
    }
  }, [content, isEditing, renderDiagram]);

  if (isEditing) {
    return (
      <NodeViewWrapper className="mermaid-block mermaid-block--editing">
        <div className="mermaid-block__header">
          <span className="mermaid-block__label">Mermaid</span>
          <button
            type="button"
            className="mermaid-block__action"
            onClick={() => {
              if (content.trim()) {
                setIsEditing(false);
              }
            }}
          >
            Render
          </button>
        </div>
        <textarea
          className="mermaid-block__editor"
          value={content}
          onChange={(e) => updateAttributes({ content: e.target.value })}
          placeholder="graph TD\n  A[Start] --> B[End]"
          rows={8}
          spellCheck={false}
        />
      </NodeViewWrapper>
    );
  }

  return (
    <NodeViewWrapper className={`mermaid-block ${selected ? "mermaid-block--selected" : ""}`}>
      <div className="mermaid-block__header">
        <span className="mermaid-block__label">Mermaid</span>
        <button
          type="button"
          className="mermaid-block__action"
          onClick={() => setIsEditing(true)}
        >
          Edit
        </button>
      </div>
      {error ? (
        <div className="mermaid-block__error">{error}</div>
      ) : (
        <div
          ref={containerRef}
          className="mermaid-block__svg"
          // SVG is generated by mermaid.render() with securityLevel: "strict",
          // which sanitizes the output. This is safe trusted content.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      )}
    </NodeViewWrapper>
  );
}

// The TipTap extension
export const MermaidBlock = Node.create({
  name: "mermaidBlock",
  group: "block",
  atom: true,

  addAttributes() {
    return {
      content: {
        default: "",
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'div[data-type="mermaid-block"]',
      },
    ];
  },

  renderHTML({ HTMLAttributes }: { HTMLAttributes: Record<string, unknown> }) {
    return ["div", mergeAttributes(HTMLAttributes, { "data-type": "mermaid-block" }), 0];
  },

  addNodeView() {
    return ReactNodeViewRenderer(MermaidNodeView);
  },
});
